### ISSUE TITLE
pytest failed

### ISSUE THREAD

**Issue by unacanal** [unerue/lightning-boilerplate#1]
I cloned the repo and followed the instruction as in README.md.
Also runned `poetry install`. But when I try to `pytest test`, it shows error like this.

```
root@e26b5af13215:/workspace/lightning-boilerplate# pytest test
ImportError while loading conftest '/workspace/lightning-boilerplate/tests/conftest.py'.
tests/conftest.py:6: in <module>
    import rootutils
E   ModuleNotFoundError: No module named 'rootutils'
```

I've tried 
`poetry pytest test` 
and it works.

Do you know why?

**Comment by unerue** [comment]
Thanks for your comment, you will run just the command `poetry run pytest`. We are writing detailed instructions on how to use it. We apologize for any inconvenience.

**Comment by unacanal** [comment]
I see. Thank you for your reply :D
